### ISSUE TITLE
SyntaxError at src/editors/cleanup/control-blocks-container.js

### ISSUE THREAD

**Issue by juancho0202** [openscd/open-scd#1145]
**Describe the bug**
The clean up plugin seems to struggle with some particular LN selectors. The following stack trace was caught by Elastic monitoring:

```console
Unhandled promise rejection: SyntaxError: Failed to execute 'querySelector' on 'Element': 'DataSet[name=Relay_FIELDAApplication/LLN0$BR$A_BRCB_23]' is not a valid selector.
at <anonymous> (src/editors/cleanup/control-blocks-container.js:181:36)
at renderUnreferencedControls (src/editors/cleanup/control-blocks-container.js:178:129)
at render (src/editors/cleanup/control-blocks-container.js:224:36)
at update (_snowpack/pkg/common/lit-element-d8235cfe.js:1749:37)
at performUpdate (_snowpack/pkg/common/lit-element-d8235cfe.js:951:22)
at _enqueueUpdate (_snowpack/pkg/common/lit-element-d8235cfe.js:904:29)
```

**Comment by juancho0202** [comment]
Unfortunately the monitoring tool doesn't catch the particular SCL file that was being used by the user at the time the error was thrown so it may be tricky to reproduce.
